#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0 > /dev/null 2>&1
runApplication blockMesh
#runApplication setSet -batch createObstacle.setSet
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch walls
runApplication setFields
runApplication decomposePar
runParallel `getApplication` 2
reconstructParMesh -mergeTol 1e-06
runApplication reconstructPar

tOld=`cat system/controlDict | grep "endTime " | tr -d 'endTime     ' | tr -d ';'`
tNew=`echo $tOld + 0.02 | bc`
sed -i -e "s/endTime         $tOld;/endTime         $tNew;/g" system/controlDict
rm -rf log.*
rm -rf processor*
# 

# runApplication blockMesh
# runApplication topoSet
# runApplication subsetMesh -overwrite c0 -patch walls
# runApplication setFields
runApplication decomposePar
runParallel `getApplication` 2
reconstructParMesh -mergeTol 1e-06
runApplication reconstructPar

tOld=`cat system/controlDict | grep "endTime " | tr -d 'endTime     ' | tr -d ';'`
tNew=`echo $tOld + 0.02 | bc`
sed -i -e "s/endTime         $tOld;/endTime         $tNew;/g" system/controlDict
rm -rf log.*
rm -rf processor*
# 
 
# runApplication blockMesh
# runApplication topoSet
# runApplication subsetMesh -overwrite c0 -patch walls
# runApplication setFields
runApplication decomposePar
runParallel `getApplication` 2
reconstructParMesh -mergeTol 1e-06
runApplication reconstructPar
tOld=`cat system/controlDict | grep "endTime " | tr -d 'endTime     ' | tr -d ';'`
tNew=`echo $tOld + 0.02 | bc`
sed -i -e "s/endTime         $tOld;/endTime         $tNew;/g" system/controlDict
rm -rf log.*
rm -rf processor*

# runApplication decomposePar
# runParallel `getApplication` 2
# reconstructParMesh -mergeTol 1e-06
# runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
